server:
  port: 19090

spring:
  application:
    name: eureka-service

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:19090/eureka
  instance:
    hostname: localhost
