server:
  port: 19091

spring:
  main:
    web-application-type: reactive  # Spring 애플리케이션이 리액티브 웹 애플리케이션으로 설정됨
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: product-service  # 라우트 식별자
          uri: lb://product-service  # 'product-service' 라는 이름으로 로드 밸런싱된 서비스로 라우팅
          predicates:
            - Path=/products/**  # /products/** 경로로 들어오는 요청을 이 라우트로 처리
      discovery:
        locator:
          enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka
